<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-22T12:30:28 BST" name="Surefire suite" finished-at="2022-06-22T12:30:28 BST" duration-ms="34">
    <groups>
    </groups>
    <test started-at="2022-06-22T12:30:28 BST" name="Surefire test" finished-at="2022-06-22T12:30:28 BST" duration-ms="34">
      <class name="com.idera.testrail.tests.SubtractionTests">
        <test-method signature="SubtractTwoNumbers()[pri:0, instance:com.idera.testrail.tests.SubtractionTests@1ff4931d]" started-at="2022-06-22T12:30:28 BST" name="SubtractTwoNumbers" finished-at="2022-06-22T12:30:28 BST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubtractTwoNumbers -->
      </class> <!-- com.idera.testrail.tests.SubtractionTests -->
      <class name="com.idera.testrail.tests.MultiplicationTest">
        <test-method signature="MultiplyTwoNumbers()[pri:0, instance:com.idera.testrail.tests.MultiplicationTest@367ffa75]" started-at="2022-06-22T12:30:28 BST" name="MultiplyTwoNumbers" finished-at="2022-06-22T12:30:28 BST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MultiplyTwoNumbers -->
      </class> <!-- com.idera.testrail.tests.MultiplicationTest -->
      <class name="com.idera.testrail.tests.SumTests">
        <test-method signature="AddTwoNumbers()[pri:0, instance:com.idera.testrail.tests.SumTests@65e98b1c]" started-at="2022-06-22T12:30:28 BST" name="AddTwoNumbers" finished-at="2022-06-22T12:30:28 BST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddTwoNumbers -->
        <test-method signature="AddTwoNumbersWithDecimals()[pri:0, instance:com.idera.testrail.tests.SumTests@65e98b1c]" started-at="2022-06-22T12:30:28 BST" name="AddTwoNumbersWithDecimals" finished-at="2022-06-22T12:30:28 BST" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1.5+1.4 should equal 3 expected [2.9] but found [3.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1.5+1.4 should equal 3 expected [2.9] but found [3.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEquals(Assert.java:727)
at com.idera.testrail.tests.SumTests.AddTwoNumbersWithDecimals(SumTests.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddTwoNumbersWithDecimals -->
      </class> <!-- com.idera.testrail.tests.SumTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
